# Generated by Django 3.1.3 on 2022-05-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
                ('answer', models.CharField(default='', max_length=20)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
